[estimation]
  estimator_port = 502
  estimator_host = "hoge.com"
[run_group]

  [run_group.periodic_tasks]
    [run_group.periodic_tasks.poller]
      period = "500ms"
    [run_group.periodic_tasks.poller.params]
      enable_test_mode = true
      edge = "polling_test_edge"
      device = "polling_test_device"
      endpoint = "localhost:3001"
      normal_period = "500ms"
      idle_period = "500ms"
    [run_group.periodic_tasks.version_log]
      period = "10s"
    [run_group.periodic_tasks.metrics_log]
      period = "10s"
    [run_group.periodic_tasks.metrics_log.params]
      file_dir = "/shares/metrics"

  [run_group.internal_job_servers]
    [run_group.internal_job_servers.multi_auto_server]

  [run_group.api_servers]
    [run_group.api_servers.cloud_mock]
      [run_group.api_servers.cloud_mock.params]
        host = "0.0.0.0"
        port = 3000

[com]
  [com.qmt]
    port = "2230"


